name: Test Docker Image
on:
  push:

jobs:
  test:
    name: Docker test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker-compose build

    - name: Test docker image CLI
      run: "[[ $(docker-compose run redirectly --version) =~ [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ ]]"
